version: '3'
services:
  sql:
    image: mariadb
    container_name: kommandr-api-sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kommandr
      MYSQL_DATABASE: kommandr
      MYSQL_USER: kommandr
      MYSQL_PASSWORD: k0mm4ndr
    networks:
      - backend
  mongodb:
    image: mongo
    container_name: kommandr-api-mongodb
    ports: 
      - "27017:27017"
    networks:
      - backend
  recommendr:
    build: src/backend/recommendr
    container_name: kommandr-recommendr
    networks:
      - backend
    ports:
      - "7070:7070"
networks:
  backend:
