version: '3'
services:
  sql:
    image: mariadb
    container_name: kommandr-api-sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kommandr
      MYSQL_DATABASE: kommandr
      MYSQL_USER: kommandr
      MYSQL_PASSWORD: k0mm4ndr
    networks:
      - backend
  mongodb:
    image: mongo
    container_name: kommandr-api-mongodb
    ports: 
      - "27017:27017"
    networks:
      - backend
  recommendr:
    build: src/backend/recommendr
    container_name: kommandr-recommendr
    networks:
      - backend
    ports:
      - "7070:7070"
  api:
    build:
      context: ./src/backend/api
    container_name: kommandr-api
    depends_on:
      - sql
      - mongodb
    environment:
      NODE_ENV: production
      KMDR_API_SQL_HOST: kommandr-api-sql
      KMDR_API_SQL_PORT: 3306
      KMDR_API_MONGODB_HOST: kommandr-api-mongodb
      KMDR_API_MONGODB_PORT: 27017
      KMDR_API_RECOMMENDR_HOST: http://kommandr-recommendr
      KMDR_API_RECOMMENDR_PORT: 7070
    networks:
      - backend
    ports: 
      - "80:5001"
    working_dir: /home/node/api
    command: npm run build
networks:
  backend:
