#import "../fragments/kommandrInfo.gql"
#import "../fragments/kommandrStats.gql"

query searchKommandr($query: String) {
  allKommandrs (title: $query, cli: $query, description: $query) {
    ...kommandrInfo
    ...kommandrStats
  }
}